name: forecasting_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - plotly
  - statsmodels
  - scikit-learn
  - optuna
  - prophet
  - pip
  - pip:
      - kaleido